apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-cisco-secrets
          volumeMounts:
            - name: app-storage
              mountPath: /app/data
            - name: configs-storage
              mountPath: /app/configs
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-pvc
        - name: configs-storage
          emptyDir: {}
