apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cisco-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  CISCO_USER: {{ .Values.ciscoCredentials.user | quote }}
  CISCO_PASSWORD: {{ .Values.ciscoCredentials.password | quote }}
  CISCO_ENABLE: {{ .Values.ciscoCredentials.enableSecret | quote }}
