name: NetDevOps Cisco ACL GitOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Setup Environment & Deploy Stack
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Install System Dependencies & Docker Compose
        run: |
          echo "Удаление битого репозитория HashiCorp..."
          sudo rm -f /etc/apt/sources.list.d/*hashicorp* || true

          echo "Обновление репозиториев и установка Compose..."
          sudo apt update -y || true
          sudo apt install -y --no-install-recommends docker-compose-plugin git curl 


      - name: Ensure User Permissions for Docker
        run: |
          sudo usermod -aG docker $USER || true

      - name: Deploy Containers via Docker Compose
        run: |
          echo "Запуск контейнеров проекта..."
          docker compose up -d --build

      - name: Check Running Containers
        run: |
          docker ps
